# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_patient_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage_info', models.CharField(max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=400)),
                ('date', models.DateTimeField(verbose_name='test time')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Patient')),
            ],
        ),
    ]
