# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
