# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20161114_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted', to='registration.Hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Hospital'),
            preserve_default=False,
        ),
    ]
