# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20161205_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
