# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0012_remove_patient_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='appointment time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Doctor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Hospital')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Patient')),
            ],
        ),
    ]
